# translation of apt-listchanges to French
# Copyright (C) 2008 Christian Perrier <bubulle@debian.org>
#
# Christian Perrier <bubulle@debian.org>, 2004, 2006, 2008, 2010.
# Jean-Pierre Giraud <jean-pierregiraud@neuf.fr>, 2017.
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: apt-listchanges@packages.debian.org\n"
"POT-Creation-Date: 2019-11-03 20:05+0100\n"
"PO-Revision-Date: 2017-01-23 17:55+0100\n"
"Last-Translator: Jean-Pierre Giraud <jean-pierregiraud@neuf.fr>\n"
"Language-Team: French <debian-l10n-french@lists.debian.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Lokalize 1.5\n"
"Plural-Forms: Plural-Forms: nplurals=2; plural=n>1;\n"

#: ../apt-listchanges.py:62
#, python-format
msgid "Unknown frontend: %s"
msgstr "Interface inconnue : %s"

#: ../apt-listchanges.py:78
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr "Impossible de réouvrir /dev/tty pour l'entrée standard : %s"

#: ../apt-listchanges.py:133
#, python-format
msgid "News for %s"
msgstr "Nouveautés pour %s"

#: ../apt-listchanges.py:135
#, python-format
msgid "Changes for %s"
msgstr "Modifications pour %s"

#: ../apt-listchanges.py:145
msgid "Informational notes"
msgstr "Notes d'information"

#: ../apt-listchanges.py:152
msgid "apt-listchanges: News"
msgstr "apt-listchanges : nouveautés"

#: ../apt-listchanges.py:153
msgid "apt-listchanges: Changelogs"
msgstr "apt-listchanges : journaux des modifications (« changelogs »)"

#: ../apt-listchanges.py:159
#, python-format
msgid "apt-listchanges: news for %s"
msgstr "apt-listchanges : nouveautés pour %s"

#: ../apt-listchanges.py:160
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr "apt-listchanges : journaux des modifications (« changelogs ») pour %s"

#: ../apt-listchanges.py:166
msgid "Didn't find any valid .deb archives"
msgstr "Impossible de trouver une archive .deb valable"

#: ../apt-listchanges.py:183
#, python-format
msgid "%s: will be newly installed"
msgstr "%s : sera installé pour la première fois"

#: ../apt-listchanges.py:210
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr "%(pkg)s : la version %(version)s a déjà été vue"

#: ../apt-listchanges.py:214
#, fuzzy, python-format
#| msgid "%(pkg)s: Version %(version)s has already been seen"
msgid ""
"%(pkg)s: Version %(version)s is lower than version of related packages "
"(%(maxversion)s)"
msgstr "%(pkg)s : la version %(version)s a déjà été vue"

#: ../apt-listchanges.py:268
msgid "Binary NMU of"
msgstr ""

#: ../apt-listchanges.py:302
#, python-format
msgid "Received signal %d, exiting"
msgstr "Signal %d reçu, sortie"

#: ../apt-listchanges/apt_listchanges.py:55
msgid "Aborting"
msgstr "Abandon"

#: ../apt-listchanges/apt_listchanges.py:60
#, python-format
msgid "Confirmation failed: %s"
msgstr "Échec de confirmation : %s"

#: ../apt-listchanges/apt_listchanges.py:64
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr "Envoi des modifications par courriel à %(address)s : %(subject)s"

#: ../apt-listchanges/apt_listchanges.py:83
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr "Échec d'envoi du courriel à %(address)s : %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:92
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr "L'interface courriel a besoin d'un « sendmail » installé, utilise %s"

#: ../apt-listchanges/apt_listchanges.py:98
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr "L'interface courriel a besoin d'une adresse de courriel, utilise %s"

#: ../apt-listchanges/apt_listchanges.py:111
msgid "Available apt-listchanges frontends:"
msgstr "Interfaces d'apt-listchanges disponibles :"

#: ../apt-listchanges/apt_listchanges.py:113
msgid "Choose a frontend by entering its number: "
msgstr "Sélectionner une interface en entrant son numéro :"

#: ../apt-listchanges/apt_listchanges.py:122
#: ../apt-listchanges/apt_listchanges.py:431
#, python-format
msgid "Error: %s"
msgstr "Erreur : %s"

#: ../apt-listchanges/apt_listchanges.py:124
#, python-format
msgid "Using default frontend: %s"
msgstr "Utilise l'interface par défaut : %s"

#: ../apt-listchanges/apt_listchanges.py:167
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr "$DISPLAY n'est pas défini, retour à %(frontend)s"

#: ../apt-listchanges/apt_listchanges.py:187
#, python-format
msgid ""
"The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""
"L'interface GTK a besoin de python3-gi,\n"
"mais il ne peut être chargé. Retour à %(frontend)s.\n"
"L'erreur est : %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:288
msgid "Do you want to continue? [Y/n] "
msgstr "Souhaitez-vous continuer ? [O/n]  "

#: ../apt-listchanges/apt_listchanges.py:301
#: ../apt-listchanges/apt_listchanges.py:327
#: ../apt-listchanges/apt_listchanges.py:335
msgid "Reading changelogs"
msgstr "Lecture des fichiers de modifications (« changelog »)"

#: ../apt-listchanges/apt_listchanges.py:335
msgid "Done"
msgstr "Terminé"

#: ../apt-listchanges/apt_listchanges.py:368
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr "La commande %(cmd)s s'est achevée avec l'état %(status)d"

#: ../apt-listchanges/apt_listchanges.py:413
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr "Utilisateur trouvé : %(user)s, répertoire temporaire : %(dir)s"

#: ../apt-listchanges/apt_listchanges.py:459
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr ""
"Impossible de trouver un utilisateur à partir de la variable '%(envvar)s':\n"
"%(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:465
msgid "Cannot find suitable user to drop root privileges"
msgstr ""
"Pas d'utilisateur approprié pour abandonner les droits du superutilisateur"

#: ../apt-listchanges/apt_listchanges.py:491
#, python-format
msgid ""
"None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr "Pas de répertoire accessible à l'utilisateur %(user)s : %(dirs)s"

#: ../apt-listchanges/apt_listchanges.py:521
msgid "press q to quit"
msgstr "Tapez q pour quitter"

#: ../apt-listchanges/ALCConfig.py:88
#, python-format
msgid "Unknown configuration file option: %s"
msgstr "Option inconnue dans le fichier de configuration : %s"

#: ../apt-listchanges/ALCConfig.py:101
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr "Syntaxe : apt-listchanges [options] {--apt | fichier.deb ...}\n"

#: ../apt-listchanges/ALCConfig.py:107
#, python-format
msgid "Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""
"Argument %(arg)s inconnu pour l'option %(opt)s. Les valeurs permises sont :\n"
"%(allowed)s."

#: ../apt-listchanges/ALCConfig.py:119
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr "%(deb)s ne possède pas l'extension '.deb'"

#: ../apt-listchanges/ALCConfig.py:122
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr "%(deb)s n'existe pas ou n'est pas un fichier"

#: ../apt-listchanges/ALCConfig.py:125
#, python-format
msgid "%(deb)s is not readable"
msgstr "%(deb)s n'est pas lisible"

#: ../apt-listchanges/ALCConfig.py:216
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:224
#, fuzzy
#| msgid "--since=<version> expects a only path to a .deb"
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr "--since=<version> a besoin du chemin d'accès à un fichier .deb"

#: ../apt-listchanges/DebianFiles.py:119 ../apt-listchanges/DebianFiles.py:128
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr "Erreur de traitement de '%(what)s': %(errmsg)s"

#: ../apt-listchanges/DebianFiles.py:337
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr "« %s » ignoré (semble être un répertoire)"

#: ../apt-listchanges/DebianFiles.py:410
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:414
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed "
"with: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:420
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get "
"changelog': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:40
msgid "apt-listchanges: Reading changelogs"
msgstr ""
"apt-listchanges : lecture des journaux de modifications (« changelogs »)"

#: ../apt-listchanges/AptListChangesGtk.py:41
msgid "Reading changelogs. Please wait."
msgstr "Lecture des journaux de modifications. Veuillez patienter."

#: ../apt-listchanges/AptListChangesGtk.py:74
msgid "Continue Installation?"
msgstr "Faut-il poursuivre l'installation ?"

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid ""
"Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt-listchanges/ALCApt.py:55
msgid "APT pipeline messages:"
msgstr "Messages du tube d'APT :"

#: ../apt-listchanges/ALCApt.py:63
msgid "Packages list:"
msgstr "Liste des paquets :"

#: ../apt-listchanges/ALCApt.py:71
msgid ""
"APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""
"La variable d'environnement APT_HOOK_INFO_FD n'est pas définie\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD est-il bien à 20 ?)"

#: ../apt-listchanges/ALCApt.py:77
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr ""
"Valeur incorrecte de la variable d'environnement APT_HOOK_INFO_FD (non\n"
"numérique)"

#: ../apt-listchanges/ALCApt.py:80
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""
"Les messages du tube d'apt seront lus à partir du descripteur de fichier %d"

#: ../apt-listchanges/ALCApt.py:83
msgid ""
"Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. "
"aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly "
"updated."
msgstr ""
"Valeur incorrecte (0) de la variable d'environnement APT_HOOK_INFO_FD.\n"
"Si l'avertissement persiste après avoir redémarré le gestionnaire\n"
"de paquets (aptitude par exemple), veuillez vérifier si le fichier\n"
"/etc/apt/apt.conf.d/20listchanges a été correctement mis à jour."

#: ../apt-listchanges/ALCApt.py:88
msgid ""
"APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater "
"than 2)."
msgstr ""
"La variable d'environnement APT_HOOK_INFO_FD est mal définie\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD devrait être\n"
"supérieur à 2)."

#: ../apt-listchanges/ALCApt.py:94
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr ""
"Lecture impossible à partir du descripteur de fichier %(fd)d : %(errmsg)s"

#: ../apt-listchanges/ALCApt.py:100
msgid ""
"Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""
"VERSION incorrecte ou manquante dans l'affichage d'apt\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version est-il bien à 2 ?)"

#: ../apt-listchanges/ALCLog.py:30 ../apt-listchanges/ALCLog.py:36
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr "apt-listchanges : %(msg)s"

#: ../apt-listchanges/ALCLog.py:33
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr "avertissement d'apt-listchanges : %(msg)s"

#: ../apt-listchanges/ALCSeenDb.py:55
msgid ""
"Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""
"Le chemin de la base de données des déjà-vus est inconnu.\n"
"Veuillez l'indiquer avec l'option --save-seen\n"
"ou passer l'option --profile=apt pour qu'il soit lu à partir du fichier de\n"
"configuration."

#: ../apt-listchanges/ALCSeenDb.py:66
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr "Le nom de la base de données %(db)s ne se termine pas par %(ext)s"

#: ../apt-listchanges/ALCSeenDb.py:75
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr "Échec du chargement de la base de données %(db)s: %(errmsg)s"

#: ../apt-listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr "Liste des modifications"

#: ../apt-listchanges/apt-listchanges.ui:43
msgid ""
"The following changes are found in the packages you are about to install:"
msgstr ""
"Les modifications suivantes ont été découvertes dans les paquets que vous\n"
"allez installer :"

#~ msgid "You can abort the installation if you select 'no'."
#~ msgstr "Vous pouvez interrompre l'installation en répondant négativement."

#~ msgid "The %s frontend is deprecated, using pager"
#~ msgstr "L'interface %s est obsolète, utilisation de l'afficheur page à page"

#~ msgid "Confirmation failed, don't save seen state"
#~ msgstr "Échec de la confirmation, état vu (« seen ») non sauvegardé"

#~ msgid "Can't set locale; make sure $LC_* and $LANG are correct!\n"
#~ msgstr ""
#~ "Impossible de charger la « locale » : veuillez contrôler les\n"
#~ "variables $LC_* et $LANG.\n"
