# translation of ru.po to Russian
#    Translators, if you are not familiar with the PO format, gettext
#    documentation is worth reading, especially sections dedicated to
#    this format, e.g. by running:
#         info -n '(gettext)PO Files'
#         info -n '(gettext)Header Entry'
#    Some information specific to po-debconf are available at
#            /usr/share/doc/po-debconf/README-trans
#         or http://www.debian.org/intl/l10n/po-debconf/README-trans#
#    Developers do not need to manually edit POT or PO files.
#
# Ilgiz Kalmetev <translator@ilgiz.pp.ru>, 2003.
# Yuri Kozlov <kozlov.y@gmail.com>, 2008.
# Sergey Alyoshin <alyoshin.s@gmail.com>, 2014.
# Galina Anikina <merilaga@yandex.ru>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: apt-listchanges NEW\n"
"Report-Msgid-Bugs-To: apt-listchanges@packages.debian.org\n"
"POT-Creation-Date: 2019-11-03 20:05+0100\n"
"PO-Revision-Date: 2018-03-04 23:48+0500\n"
"Last-Translator: Galina Anikina <merilaga@yandex.ru>\n"
"Language-Team: Debian L10n Russian <debian-l10n-russian@lists.debian.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.6\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../apt-listchanges.py:62
#, python-format
msgid "Unknown frontend: %s"
msgstr "Неизвестный просмотрщик: %s"

#: ../apt-listchanges.py:78
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr "Не могу переоткрыть /dev/tty для стандартного потока ввода: %s"

#: ../apt-listchanges.py:133
#, python-format
msgid "News for %s"
msgstr "Новости о %s"

#: ../apt-listchanges.py:135
#, python-format
msgid "Changes for %s"
msgstr "Изменения в %s"

#: ../apt-listchanges.py:145
msgid "Informational notes"
msgstr "Замечания справочного характера"

#: ../apt-listchanges.py:152
msgid "apt-listchanges: News"
msgstr "apt-listchanges: Новости"

#: ../apt-listchanges.py:153
msgid "apt-listchanges: Changelogs"
msgstr "apt-listchanges: Журналы изменений"

#: ../apt-listchanges.py:159
#, python-format
msgid "apt-listchanges: news for %s"
msgstr "apt-listchanges: новости о %s"

#: ../apt-listchanges.py:160
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr "apt-listchanges: журналы изменений %s"

#: ../apt-listchanges.py:166
msgid "Didn't find any valid .deb archives"
msgstr "Допустимые .deb архивы не найдены"

#: ../apt-listchanges.py:183
#, python-format
msgid "%s: will be newly installed"
msgstr "%s: будет установлен заново"

#: ../apt-listchanges.py:210
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr "%(pkg)s: Версия %(version)s уже встречалась"

#: ../apt-listchanges.py:214
#, python-format
msgid ""
"%(pkg)s: Version %(version)s is lower than version of related packages "
"(%(maxversion)s)"
msgstr ""
"%(pkg)s: Версия %(version)s меньше номера версии связанных пакетов "
"(%(maxversion)s)"

#: ../apt-listchanges.py:268
msgid "Binary NMU of"
msgstr ""

#: ../apt-listchanges.py:302
#, python-format
msgid "Received signal %d, exiting"
msgstr "Получен сигнал %d, завершение работы"

#: ../apt-listchanges/apt_listchanges.py:55
msgid "Aborting"
msgstr "Аварийное завершение"

#: ../apt-listchanges/apt_listchanges.py:60
#, python-format
msgid "Confirmation failed: %s"
msgstr "Произошла ошибка при подтверждении: %s"

#: ../apt-listchanges/apt_listchanges.py:64
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr "Отправка почты %(address)s: %(subject)s"

#: ../apt-listchanges/apt_listchanges.py:83
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr "Не удалось отправить почту по адресу %(address)s: %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:92
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr "Для просмотрщика почты требуется установить 'sendmail', используя %s"

#: ../apt-listchanges/apt_listchanges.py:98
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr ""
"Для просмотрщика почты требуется указать адрес электронной почты, используя "
"%s"

#: ../apt-listchanges/apt_listchanges.py:111
msgid "Available apt-listchanges frontends:"
msgstr "Доступные просмотрщики apt-listchanges:"

#: ../apt-listchanges/apt_listchanges.py:113
msgid "Choose a frontend by entering its number: "
msgstr "Для изменения просмотрщика введите его номер: "

#: ../apt-listchanges/apt_listchanges.py:122
#: ../apt-listchanges/apt_listchanges.py:431
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: ../apt-listchanges/apt_listchanges.py:124
#, python-format
msgid "Using default frontend: %s"
msgstr "Используется просмотрщик по умолчанию: %s"

#: ../apt-listchanges/apt_listchanges.py:167
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr "Переменная $DISPLAY не установлена, возврат в %(frontend)s"

#: ../apt-listchanges/apt_listchanges.py:187
#, python-format
msgid ""
"The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""
"Просмотрщику GTK требуется рабочий python3-gi,\n"
"но он не был найден. Возврат в %(frontend)s.\n"
"Ошибка: %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:288
msgid "Do you want to continue? [Y/n] "
msgstr "Хотите продолжить? [Y/n] "

#: ../apt-listchanges/apt_listchanges.py:301
#: ../apt-listchanges/apt_listchanges.py:327
#: ../apt-listchanges/apt_listchanges.py:335
msgid "Reading changelogs"
msgstr "Чтение журналов изменений"

#: ../apt-listchanges/apt_listchanges.py:335
msgid "Done"
msgstr "Выполнено"

#: ../apt-listchanges/apt_listchanges.py:368
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr "Команда %(cmd)s завершила работу с результатом %(status)d"

#: ../apt-listchanges/apt_listchanges.py:413
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr "Найден пользователь: %(user)s, временный каталог: %(dir)s"

#: ../apt-listchanges/apt_listchanges.py:459
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr ""
"Ошибка получения имени пользователя из переменной '%(envvar)s': %(errmsg)s"

#: ../apt-listchanges/apt_listchanges.py:465
msgid "Cannot find suitable user to drop root privileges"
msgstr ""
"Не удаётся найти подходящего пользователя для перехода от суперпользователя"

#: ../apt-listchanges/apt_listchanges.py:491
#, python-format
msgid ""
"None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr ""
"Ни один из следующих каталогов не открыт для доступа пользователю %(user)s: "
"%(dirs)s"

#: ../apt-listchanges/apt_listchanges.py:521
msgid "press q to quit"
msgstr "нажмите q для выхода"

#: ../apt-listchanges/ALCConfig.py:88
#, python-format
msgid "Unknown configuration file option: %s"
msgstr "Неизвестная опция файла настройки: %s"

#: ../apt-listchanges/ALCConfig.py:101
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr "Использование: apt-listchanges [опции] {--apt | имя_файла.deb ...}\n"

#: ../apt-listchanges/ALCConfig.py:107
#, python-format
msgid "Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""
"Неизвестный аргумент %(arg)s опции %(opt)s. Допустимые значения: %(allowed)s."

#: ../apt-listchanges/ALCConfig.py:119
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr "%(deb)s не имеет расширения '.deb' в названии файла"

#: ../apt-listchanges/ALCConfig.py:122
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr "%(deb)s не существует или не является файлом"

#: ../apt-listchanges/ALCConfig.py:125
#, python-format
msgid "%(deb)s is not readable"
msgstr "%(deb)s не доступен для чтения"

#: ../apt-listchanges/ALCConfig.py:216
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr "опции --since=<version> и --show-all являются взаимоисключающими"

#: ../apt-listchanges/ALCConfig.py:224
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr "--since=<версия> ожидает путь только к одному архиву .deb"

#: ../apt-listchanges/DebianFiles.py:119 ../apt-listchanges/DebianFiles.py:128
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr "Ошибка при обработке '%(what)s': %(errmsg)s"

#: ../apt-listchanges/DebianFiles.py:337
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr "Игнорируется `%s' (кажется, это каталог!)"

#: ../apt-listchanges/DebianFiles.py:410
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr "Вызов %(cmd)s для загрузки журнала изменений"

#: ../apt-listchanges/DebianFiles.py:414
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed "
"with: %(errmsg)s"
msgstr ""
"Не удаётся получить журнал изменений пакета %(pkg)s; команда 'apt-get "
"changelog' \n"
"вернула следующие ошибки: %(errmsg)s"

#: ../apt-listchanges/DebianFiles.py:420
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get "
"changelog': %(errmsg)s"
msgstr ""
"Не удаётся получить журнал изменений пакета  %(pkg)s; не удалось запустить \n"
"'apt-get changelog': %(errmsg)s"

#: ../apt-listchanges/AptListChangesGtk.py:40
msgid "apt-listchanges: Reading changelogs"
msgstr "apt-listchanges: Чтение журналов изменений"

#: ../apt-listchanges/AptListChangesGtk.py:41
msgid "Reading changelogs. Please wait."
msgstr "Чтение журналов изменений. Пожалуйста, подождите."

#: ../apt-listchanges/AptListChangesGtk.py:74
msgid "Continue Installation?"
msgstr "Продолжить установку?"

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid ""
"Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt-listchanges/ALCApt.py:55
msgid "APT pipeline messages:"
msgstr "Сообщения, поступившие от APT:"

#: ../apt-listchanges/ALCApt.py:63
msgid "Packages list:"
msgstr "Список пакетов:"

#: ../apt-listchanges/ALCApt.py:71
msgid ""
"APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""
"Переменная окружения APT_HOOK_INFO_FD не определена\n"
"(значение Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD \n"
"установлено в 20?)"

#: ../apt-listchanges/ALCApt.py:77
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr "Ошибочное (не числовое) значение переменной окружения APT_HOOK_INFO_FD"

#: ../apt-listchanges/ALCApt.py:80
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""
"Будет выполняться чтение сообщений, получаемых от apt, из файлового "
"дескриптора %d"

#: ../apt-listchanges/ALCApt.py:83
msgid ""
"Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. "
"aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly "
"updated."
msgstr ""
"Некорректное значение (0) переменной окружения APT_HOOK_INFO_FD.\n"
"Если предупреждения появляются снова после перезапуска менеджера\n"
"пакетов (например aptitude), пожалуйста проверьте был ли правильно\n"
"обновлён файл /etc/apt/apt.conf.d/20listchanges."

#: ../apt-listchanges/ALCApt.py:88
msgid ""
"APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater "
"than 2)."
msgstr ""
"Переменная окружения APT_HOOK_INFO_FD определена некорректно\n"
"(значение Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD\n"
"должно быть больше чем 2)."

#: ../apt-listchanges/ALCApt.py:94
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr "Не удалось прочитать из файлового дескриптора  %(fd)d: %(errmsg)s"

#: ../apt-listchanges/ALCApt.py:100
msgid ""
"Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""
"Неправильное (или отсутствует) значение VERSION в выводе apt\n"
"(значение Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version равно 2?)"

#: ../apt-listchanges/ALCLog.py:30 ../apt-listchanges/ALCLog.py:36
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr "apt-listchanges: %(msg)s"

#: ../apt-listchanges/ALCLog.py:33
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr "Предупреждение от apt-listchanges: %(msg)s"

#: ../apt-listchanges/ALCSeenDb.py:55
msgid ""
"Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""
"Путь до просматриваемой базы данных неизвестен.\n"
"Укажите его с помощью опции --save-seen, либо добавьте опцию \n"
"--profile=apt, что позволит прочитать путь из файла настройки."

#: ../apt-listchanges/ALCSeenDb.py:66
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr "База данных %(db)s не оканчивается на %(ext)s"

#: ../apt-listchanges/ALCSeenDb.py:75
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr "Не удалось загрузить базу данных %(db)s: %(errmsg)s"

#: ../apt-listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr "Вывести изменения"

#: ../apt-listchanges/apt-listchanges.ui:43
msgid ""
"The following changes are found in the packages you are about to install:"
msgstr "В устанавливаемых пакетах были найдены следующие изменения:"

#~ msgid "You can abort the installation if you select 'no'."
#~ msgstr "Вы можете прервать установку, выбрав 'no'."
